default_language_version:
  python: python3

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [ '--py310-plus' ]
        exclude: 'src/xncml/generated/_ncml_2_2.py'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.ipynb'
      - id: fix-byte-order-marker
      - id: name-tests-test
        args: [ '--pytest-test-first' ]
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
      - id: debug-statements
      - id: pretty-format-json
        args: [ '--autofix', '--no-ensure-ascii', '--no-sort-keys' ]
        exclude: '.ipynb'
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: [ '--config-file=.yamllint.yaml' ]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [ '--fix' ]
      - id: ruff-format
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [ 'flake8-rst-docstrings' ]
        args: [ '--config=.flake8' ]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.13
    hooks:
      - id: vulture
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.14.1
#    hooks:
#      - id: mypy
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [ 'tomli' ]
        args: [ '--toml=pyproject.toml' ]
#  - repo: https://github.com/numpy/numpydoc
#    rev: v1.8.0
#    hooks:
#      - id: numpydoc-validation
#        exclude: ^docs/|^tests/
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v0.8.0
    hooks:
      - id: zizmor
        args: [ '--config=.zizmor.yml' ]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: quarterly
  skip: [ ]
  submodules: false
