# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-24.04"
  tools:
    python: 'mambaforge-23.11'
  jobs:
    pre_build:
      - sphinx-apidoc -o docs/apidoc/ --module-first src/xncml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
conda:
  environment: CI/environment-docs.yml

python:
  install:
    - method: pip
      path: .
