name: dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - flake8
  - git
  - ipykernel
  - isort
  - make
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pip
  - pytest
  - pytest-cov
  - python=3.7
  - recommonmark
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xarray
  - pip:
    - sphinx_copybutton
    - xmltodict
