name: dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - flake8
  - git
  - ipykernel
  - isort
  - make
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pip
  - pytest
  - pytest-cov
  - python=3.9
  - recommonmark
  - sphinx_rtd_theme
  - sphinx
  - bump-my-version
  - watchdog
  - flake8-rst-docstrings
  - flake8-alphabetize
  - flit
  - tox
  - coverage
  - coveralls
  - ruff
  - pre-commit

  - pip:
    - sphinx_copybutton
    - xmltodict
